CREATE TABLE solutions (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  problem_id INTEGER REFERENCES problems(id),
  problem_type INTEGER REFERENCES problem_types(id),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  worked_count INTEGER NOT NULL DEFAULT 0
);